### ISSUE TITLE
Phid fetcher error

### ISSUE THREAD

**Issue by steveworkman** [etcinit/phabulous#3]
I get the following error when Phabricator sends a story to this app:

```
Successfully connected to Phabricator over Conduit
Phabricator-Slack connector server started on port 8085
storyID=316&storyType=PhabricatorApplicationTransactionFeedStory&storyData%5BobjectPHID%5D=PHID-CMIT-6xoj432vhfuvakcimuyj&storyData%5BtransactionPHIDs%5D%5B0%5D=PHID-XACT-CMIT-caaq75jvku4r6wg&storyAuthorPHID=PHID-USER-x2goqaxi44vaa6d25ho6&storyText=steve.workman+added+a+comment+to+rFTLd92f04ac653c%3A+Fixes+schema.org+for+reviews+with+0+reviews.&epoch=1441749295
/Users/tvdashboard/dashboards/phabricator-slack-feed/node_modules/babel/node_modules/core-js/shim.js:346
  if(it == undefined)throw TypeError('Function called on null or undefined');
                     ^
TypeError: Function called on null or undefined
    at TypeError (native)
    at assertDefined (/Users/tvdashboard/dashboards/phabricator-slack-feed/node_modules/babel/node_modules/core-js/shim.js:346:28)
    at toObject (/Users/tvdashboard/dashboards/phabricator-slack-feed/node_modules/babel/node_modules/core-js/shim.js:178:20)
    at Function.o.(anonymous function) (/Users/tvdashboard/dashboards/phabricator-slack-feed/node_modules/babel/node_modules/core-js/shim.js:739:19)
    at /Users/tvdashboard/dashboards/phabricator-slack-feed/src/Conduit/PhidFetcher.js:42:35
    at Request._callback (/Users/tvdashboard/dashboards/phabricator-slack-feed/node_modules/canduit/canduit.js:96:5)
    at Request.self.callback (/Users/tvdashboard/dashboards/phabricator-slack-feed/node_modules/canduit/node_modules/request/request.js:198:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/Users/tvdashboard/dashboards/phabricator-slack-feed/node_modules/canduit/node_modules/request/request.js:1073:14)
    at Request.emit (events.js:129:20)
```

It looks like no response is coming from phabricator, I've got my config set like this:

```javascript
{
  "server": {
    "port": 8085
  },
  "slack": {
    "username": "phabricator",
    "url": "https://hooks.slack.com/services/*****/**************"
  },
  "conduit": {
    "user": "slack",
    "api": "http://server.domain.com/",
    "cert": "cli-*****************"
  },
  "misc": {
    "ignore-ca": false
  }
}
```

Any ideas?

**Comment by steveworkman** [comment]
There's no error coming back from the fetch method, it's that the response from Conduit is empty when the query is made. I added a check for a null response and it doesn't crash - though I don't get links from Phabricator in the Slack messages.

I still don't know what's actually wrong though - where it's failing or what I've done wrong

**Comment by etcinit** [comment]
Hi. It seems like the bot is failing to fetch the "More info" link for messages, which is what the API call for conduit is for. Essentially, the bot requests more info about the PHID mentioned in the story which usually contains a link. Here's what I can think of at the moment:
- A conduit version incompatibility
- A bug in the bot

There's a new version of the bot rewritten in go under the [go](https://github.com/etcinit/phabricator-slack-feed/tree/go) branch. However, I haven't written docs on how to set it up yet.
